### ISSUE TITLE
关于sysycompiler

### ISSUE THREAD

**Issue by yourfriendccy** [rid-sun/practices#1]
你好，我在Syc项目中发现了您曾经提问的提问，由于联系不上原作者，想向您请教该项目的语义动作是如何实现的？如能告知，不胜感激！

**Comment by yourfriendccy** [comment]
https://github.com/nzh63/syc

**Comment by rid-sun** [comment]
1786843257，可加我q

**Comment by rid-sun** [comment]
> 你好，我在Syc项目中发现了您曾经提问的提问，由于联系不上原作者，想向您请教该项目的语义动作是如何实现的？如能告知，不胜感激！

1786843257 可加我q

**Comment by rid-sun** [comment]
> 你好，我在Syc项目中发现了您曾经提问的提问，由于联系不上原作者，想向您请教该项目的语义动作是如何实现的？如能告知，不胜感激！

原作者的代码其实并没有语义的处理，比如写a[2][2]={{1，2}，{1，2}，2}，对于原作者的项目是可以work的，但显然这样写是错误的。
为什么没有语义的处理或者很少处理？因为大赛官网给出的测试用例都是语义正确的，如果语义错误，那不同参赛队员给出的报错信息自然是不尽相同，这样就无法判别了。

**Comment by yourfriendccy** [comment]
非常感谢您能回复我，解答了我的疑惑。祝您好运！



---原始邮件---
发件人: "Tiger ***@***.***&gt;
发送时间: 2022年7月1日(周五) 上午9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rid-sun/practices] 关于sysycompiler (Issue #1)




  
你好，我在Syc项目中发现了您曾经提问的提问，由于联系不上原作者，想向您请教该项目的语义动作是如何实现的？如能告知，不胜感激！
  
原作者的代码其实并没有语义的处理，比如写a[2][2]={{1，2}，{1，2}，2}，对于原作者的项目是可以work的，但显然这样写是错误的。
 为什么没有语义的处理或者很少处理？因为大赛官网给出的测试用例都是语义正确的，如果语义错误，那不同参赛队员给出的报错信息自然是不尽相同，这样就无法判别了。

**Comment by rid-sun** [comment]
> 非常感谢您能回复我，解答了我的疑惑。祝您好运！
> […](#)
> ---原始邮件--- 发件人: "Tiger ***@***.***&gt; 发送时间: 2022年7月1日(周五) 上午9:43 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [rid-sun/practices] 关于sysycompiler (Issue #1) 你好，我在Syc项目中发现了您曾经提问的提问，由于联系不上原作者，想向您请教该项目的语义动作是如何实现的？如能告知，不胜感激！ 原作者的代码其实并没有语义的处理，比如写a[2][2]={{1，2}，{1，2}，2}，对于原作者的项目是可以work的，但显然这样写是错误的。 为什么没有语义的处理或者很少处理？因为大赛官网给出的测试用例都是语义正确的，如果语义错误，那不同参赛队员给出的报错信息自然是不尽相同，这样就无法判别了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你如果还有什么疑问可以在这里留言，我尽我可能帮你解答一下。
